---

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch

elasticsearch_version: present

elasticsearch_max_open_files: 65535
elasticsearch_max_locked_memory: unlimited

elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_pid_dir: /var/run

elasticsearch_service_startonboot: no
elasticsearch_service_state: started

elasticsearch_install_java: "true"
elasticsearch_java_package: java-1.8.0-openjdk
elasticsearch_java_package_version: present

elasticsearch_node_master: true

elasticsearch_configuration_default:
    cluster.name: 'change_me'
    node.master: 'true'
    node.name: "{{ansible_hostname}}"
    path.conf: "{{elasticsearch_conf_dir}}"
    path.data: "{{elasticsearch_data_dir}}"
    path.work: "{{elasticsearch_work_dir}}"
    path.log: "{{elasticsearch_log_dir}}"
    path.plugins: "{{elasticsearch_plugin_dir}}"
    bootstrap.mlockall: 'true'
    network.bind_host: '0.0.0.0'
    network.publish_host: "{{ansible_default_ipv4['address']}}"
    transport.tcp.port: 9300
    http.port: 9200
    http.enabled: 'true'

elasticsearch_configuration_user:
    cluster.name: 'esearch'
