---
-
    name: Add nginx yum repository
    template:
        src=nginx.repo.j2
        dest=/etc/yum.repos.d/nginx.repo
        owner=root
        group=root
        mode=0644

-
    name: Install the nginx packages
    yum: name={{ item }} state=present
    with_items: packages
    notify:
        - restart nginx

- 
    name: Create various nginx directories
    file: path={{ item }} state=directory owner=root group=root mode=0755
    with_items:
        - /etc/nginx/conf.d
        - /etc/nginx/ssl
        - /var/log/nginx
        - /var/www
- 
    name: Create nginx main configuration file
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
    notify:
        - restart nginx

-
    name: Delete default virtual
    file: path=/etc/nginx/conf.d/default.cfg state=absent
- 
    name: Create the configurations for virtuals
    template: src=site.j2 dest=/etc/nginx/conf.d/{{ item['file_name'] }}.conf
    with_items: nginx_sites
    notify:
        - reload nginx
-
    name: Create directories for virtuals
    file: path={{nginx_log_dir}}/{{item['file_name']}} state=directory owner=root group=root mode=0755
    with_items: nginx_sites

-
    name: Create webroot and log directories for virtuals
    file: path={{nginx_log_dir}}/{{item['root']}} state=directory owner=root group=root mode=0755
    with_items: nginx_sites

-
    name: Copy certificates over
    copy: dest=/etc/nginx/ssl/{{item['dst']}} src={{item['src']}} owner=root group=root mode={{item['mode'] | default("0644")}}
    with_items: nginx_certificates
    notify:
        - reload nginx

-
    name: start the nginx service
    service: name=nginx state=started enabled=yes

