---
-
    hosts: reverse-proxy
    sudo: true
    user: ec2-user
    vars:
        ssl_cert: /etc/nginx/ssl/es.crt
        ssl_key: /etc/nginx/ssl/es.key
    roles:
        -
            role: datetime
            datetime_timezone: UTC
        - 
            role: nginx
            nginx_http_upstreams:
                es:
                    - 127.0.0.1:9200
            nginx_certificates:
                -
                    src: /home/shura/muutep/ansible/ssl/ia.crt
                    dst: es.crt
                -
                    src: /home/shura/muutep/ansible/ssl/ia.key
                    dst: es.key
                    mode: '0644'
            nginx_sites:
                -
                    server_name: es.goncharov.co
                    file_name: es_http
                    listen: 80
                    root: /var/www/es
                    auth_basic: '"hands off"'
                    auth_basic_user_file: passwords
                    location:
                        name: /
                        proxy_pass: http://es
                        proxy_redirect: 'off'

                -
                    server_name: es.goncharov.co
                    file_name: es_https
                    listen: 443 ssl
                    root: /var/www/es
                    ssl_certificate: "{{ssl_cert}}"
                    ssl_certificate_key: "{{ssl_key}}"
                    ssl_session_timeout: 5m
    tasks:
        -
            name: Add nginx user accounts
            copy:
                dest=/etc/nginx/passwords
                src=files/nginx_passwd
                owner=root
                group=root
                mode=0600
            notify:
                reload nginx


